theme: jekyll-theme-minimal
title: [Abhijeet Singh Pawar]
logo: /images/asp.jpg
description: [Data Analyst | Leveraging Python, SQL, and ML to Drive Business Insights | MASc in Computer Engineering | Passionate About Solving Real-World Problems with Data]
